import { randomUUID } from 'node:crypto';
import { eq } from 'drizzle-orm';
import { closeDb, db } from '../db';
import { users } from '../db/schema';
import { logger } from '../lib/logger';
import { closeQueue } from '../queue/emailQueue';
import { redis } from '../queue/connection';
import { createCampaign } from '../services/campaignService';

/**
 * Schedules N synthetic recipients for right now, to demonstrate behaviour when
 * a large batch lands at roughly the same time.
 *
 *   npm run loadtest -- 1000
 *
 * Pair with DRY_RUN=true so the demo isn't capped by Ethereal's own limits.
 */
async function main() {
  const count = Number(process.argv[2] ?? 1000);
  if (!Number.isFinite(count) || count <= 0) {
    throw new Error('Usage: npm run loadtest -- <recipientCount>');
  }

  // Reuse the first real user if one exists, otherwise create a load-test user.
  const existing = await db.select().from(users).limit(1);
  let userId = existing[0]?.id;

  if (!userId) {
    const id = randomUUID();
    await db.insert(users).values({
      id,
      googleSub: `loadtest-${id}`,
      email: 'loadtest@reachinbox.local',
      name: 'Load Test',
    });
    userId = id;
    logger.info({ userId }, 'Created synthetic load-test user');
  }

  const recipients = Array.from({ length: count }, (_, i) => `lead-${i + 1}-${Date.now()}@example.com`);

  const startedAt = Date.now();
  const result = await createCampaign({
    userId,
    subject: `Load test — ${count} recipients`,
    body: 'This is a load-test message generated by npm run loadtest.',
    recipients,
    startAt: new Date(),
  });

  logger.info(
    {
      recipients: result.totalRecipients,
      senders: result.senderCount,
      minDelayMs: result.effectiveMinDelayMs,
      hourlyLimitPerSender: result.effectiveHourlyLimit,
      plannedEndAt: result.plannedEndAt.toISOString(),
      enqueueMs: Date.now() - startedAt,
    },
    'Load test campaign scheduled',
  );

  // eslint-disable-next-line no-console
  console.log(
    `\nScheduled ${result.totalRecipients} emails across ${result.senderCount} senders.\n` +
      `Effective throughput: ${result.senderCount * result.effectiveHourlyLimit} emails/hour.\n` +
      `Last recipient planned for: ${result.plannedEndAt.toISOString()}\n` +
      `\nNote: the scheduler pre-spaced these at enqueue time, so the rate limiter\n` +
      `should barely fire. Watch the worker log to confirm.\n`,
  );

  await db.select().from(users).where(eq(users.id, userId)).limit(1);
}

main()
  .then(async () => {
    await closeQueue();
    await redis.quit();
    await closeDb();
    process.exit(0);
  })
  .catch(async (err) => {
    logger.error({ err }, 'Load test failed');
    process.exit(1);
  });
